# Generated by Django 4.1.2 on 2022-11-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_account_value_customuser_buying_power_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("Inidvidual", "Individual"),
                    ("Foreign Citizen", "Foreign Citizen"),
                    ("US Trust", "US Trust"),
                    ("Foreign Trust", "Foreign Trust"),
                    ("US Corporation", "US Corporation"),
                    ("Foreign Corporation", "Foreign Corpoartion"),
                    (
                        "Partnership/Limited Liability Company",
                        "Partnership/Limited Liability Company",
                    ),
                    ("Managed Futures", "Managed Futures"),
                ],
                default="Inidvidual",
                max_length=37,
            ),
        ),
    ]
