# Generated by Django 4.1.2 on 2022-11-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="symbol",
            field=models.CharField(
                default="", max_length=5, unique=True, verbose_name="Ticker symbol"
            ),
        ),
    ]
