# Generated by Django 4.1.2 on 2022-11-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_home", "0002_company_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="avg_volume",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="company",
            name="div_yield",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="company",
            name="volume",
            field=models.FloatField(),
        ),
    ]
