# Generated by Django 4.1.2 on 2022-11-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_home", "0004_alter_transaction_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("Buy", "Buy"), ("Sell", "Sell")], default="Buy", max_length=4
            ),
        ),
    ]
