# Generated by Django 4.1.2 on 2022-11-12 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_home", "0005_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 12, 20, 58, 28, 339636, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
