# Generated by Django 4.1 on 2022-11-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_home", "0006_transaction_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="corr_day_low",
            new_name="curr_day_low",
        ),
    ]
