# Generated by Django 4.1.2 on 2022-11-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_home", "0008_alter_company_curr_day_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company", name="avg_volume", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="curr_day_high",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="curr_day_low",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="prev_day_open",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="company", name="volume", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="company", name="year_high", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="company", name="year_low", field=models.FloatField(null=True),
        ),
    ]
