# Generated by Django 4.1.2 on 2022-11-19 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stock_home",
            "0009_alter_company_avg_volume_alter_company_curr_day_high_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 19, 13, 5, 40, 979871)
            ),
        ),
    ]
