# Generated by Django 4.1.2 on 2022-11-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_home", "0008_alter_company_curr_day_open"),
        ("stock_home", "0020_alter_transaction_date"),
    ]

    operations = []
