# Generated by Django 4.1.2 on 2022-11-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_home", "0021_merge_20221125_1133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="curr_day_open",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
